"""empty message

Revision ID: 809ed9d95a36
Revises: f663e6d2f4eb
Create Date: 2020-01-06 23:52:54.169319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809ed9d95a36'
down_revision = 'f663e6d2f4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('City', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('State', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('State', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('City', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
