"""empty message

Revision ID: a6a9f7c60f33
Revises: 809ed9d95a36
Create Date: 2020-01-11 20:16:54.709440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a9f7c60f33'
down_revision = '809ed9d95a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_Geners',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('gener_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gener_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'gener_id')
    )
    op.add_column('Venue', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_table('Venue_Geners')
    # ### end Alembic commands ###
