"""empty message

Revision ID: c1da32a84650
Revises: dab1fc3ea0a3
Create Date: 2020-01-11 21:19:32.738587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1da32a84650'
down_revision = 'dab1fc3ea0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_Geners_gener_id_fkey', 'Venue_Geners', type_='foreignkey')
    op.create_foreign_key(None, 'Venue_Geners', 'Gener', ['gener_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue_Geners', type_='foreignkey')
    op.create_foreign_key('Venue_Geners_gener_id_fkey', 'Venue_Geners', 'Venue', ['gener_id'], ['id'])
    # ### end Alembic commands ###
